baseURL = "nucleus-zero.github.io"
languageCode = "en-us"
theme = "nucleus-zero"
summaryLength = 25
copyright = "Nucleus Zero 2022 - All rights reserved"
enableEmoji = true
publishDir = "public"
# disqusShortname = "your-shortname-here"
# googleAnalytics = "UA-1XXXXXXX1-1"
# blog

[permalinks]
  '/blog' = ':slug/'

[params]
  logo = "/images/logo.png"
# mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"

[params.author]
  name = "Mark Curphey"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
title = "Malicious code in the software supply chain."
  subtitle = '''
A blog about how malicious code and malware gets into the software supply chain, runs inside of companies devops pipelines and finds its way into production, allowing hackers to steal data, plant backdoors, hold companies to ransom, run bitcoining mining operations and much, much more.
'''

[params.social]
  github = "nucleus-zero"
  twitter = "nucleus-zero"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about"

# SEO settings
    enableRobotsTXT = true
    canonifyURLs = true
