baseURL = "https://nucleus-zero-blog.web.app/"
languageCode = "en-us"
theme = "nucleus-zero"
summaryLength = 25
copyright = "Nucleus Zero 2022 - All rights reserved"
enableEmoji = true
publishDir = "public"
# disqusShortname = "your-shortname-here"
googleAnalytics = "UA-1XXXXXXX1-1"
rssLimit = 20
# blog

[permalinks]
  '/articles' = ':slug/'

[params]
  logo = "/images/logo.png"
# mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"

[params.author]
  name = "Mark Curphey"
  thumbnail = "/images/author.png"

[params.index]
title = "Malicious code in the software supply chain."
  subtitle = '''Why and how the modern software supply chain is being used by cyber criminals and state sponsored hackers to break into companies, hold them ransom and steal their data. 
'''
  alertbar = true

[params.social]
  linkedin = "nucleus-zero"
  twitter = "nucleuszero"
  rss="index.xml"

## Main Menu
[[menu.main]]
    name = "Articles"
    weight = 100
    identifier = "articles"
    url = "/articles/"
[[menu.main]]
    name = "Events & Speaking"
    weight = 200
    identifier = "blog"
    url = "/events"
[[menu.main]]
    name = "Newsletter"
    weight = 300
    identifier = "newsletter"
    url = "/newsletter"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 400
    url = "/about"
# SEO settings
    enableRobotsTXT = true
    canonifyURLs = true